name: Build Android App

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Generate Keystore if missing
      run: |
        if [ ! -f "app/release.keystore" ]; then
          echo "Keystore not found. Generating a new one..."
          keytool -genkey -v -keystore app/release.keystore -alias wbankir -keyalg RSA -keysize 2048 -validity 10000 -storepass wbankir123 -keypass wbankir123 -dname "CN=WBankir, OU=Dev, O=WBankir, L=Moscow, S=Moscow, C=RU"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add app/release.keystore
          git commit -m "Auto-generate release.keystore"
          git push
        fi

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Signed APK
      run: ./gradlew assembleRelease

    - name: Build Signed AAB
      run: ./gradlew bundleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: app/build/outputs/apk/release/app-release.apk

    - name: Upload AAB
      uses: actions/upload-artifact@v4
      with:
        name: app-release-aab
        path: app/build/outputs/bundle/release/app-release.aab
